server:
  # address: ts_1
  address: 127.0.0.1
  user: ubuntu
  home_dir: /home/ubuntu/test/

source:
  home_dir: ./test_assets/
  binaries:
    - s_config_center
  config_files:
    - s_config_center.xini
  config_values:
    BindAddressForDevice4: 0.0.0.0:10100
    BindAddressForDevice6: "[2402:4e00:101a:f300:0:9f95:4b15:c0db]:10100"
    ServerListDownloadAddress: 127.0.0.1:10201
  data_files:
    - ip-loc.BIN
    - ip-loc-region-list.csv
  scripts:
  install_script: 
